language:
  python

python:
  - 3.7

before_install:

install:
  - pip install xlrd
  - pip install flatbuffers

script:
  - echo stop the build if there are Python syntax errors or undefined names
  - echo ; echo -n "excel2Flat testing on python version; python -V
  - python run.py

after_success:
  - echo "Build successful"