language:
  python

python:
  - 3.7

before_install:


install:
  - pip install -r requirements.txt

script:
  - echo stop the build if there are Python syntax errors or undefined names
  - python -V
  - pwd
  - ./flatc/flatc --python -o /home/travis/build/xuyiwenak/excel2Flat/generated_python generated_fbs/DemoTest.fbs --gen-onefile

after_success:
  - echo "Build successful"