language:
  python

python:
  - 3.7

before_install:
  - git clone https://github.com/google/flatbuffers.git
  - cd flatbuffers
  - mkdir build && cd build
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release .. && make -j2 && cd ..
  - cd $TRAVIS_BUILD_DIR

install:
  - pip install -r requirements.txt

script:
  - echo stop the build if there are Python syntax errors or undefined names
  - python -V
  - python run.py

after_success:
  - echo "Build successful"