language:
  python

python:
  - 3.7

before_install:

install:
  - pip install -r requirements.txt

script:
  - echo stop the build if there are Python syntax errors or undefined names
  - python -V
  - python run.py

after_success:
  - echo "Build successful"