language:
  python

python:
  - 3.7

before_install:
  - sh build_flatc.sh

install:
  - pip install -r requirements.txt

script:
  - echo stop the build if there are Python syntax errors or undefined names
  - python -V
  - python run.py -t yaml -p config.yml
  - python run.py -t json -p config.json


after_success:
  - echo "Build successful"